version: "3"
services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "80:80"
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
    container_name: back-end
    ports:
      - "3000:3000"
