version: "3"
services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "80:80"
    depends_on:
      - back-end
  back-end:
    build:
      context: ./back-end
    container_name: back-end

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf    <-- Adjust this path as needed
    ports:
      - "8080:80"
    depends_on:
      - front-end
