version: "3"
services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    restart: unless-stopped

  back-end:
    build:
      context: ./back-end
    container_name: back-end
    restart: unless-stopped
    environment:
      - POSTGRES_URI=postgres://postgres:CHsB0Xjae7V2MuRIr81YodRZ2jA0wHFl0HGnNtCMcsipJ8HDuHKV5ZMUprHjTlBx@zc0wco8:5432/request_bin
      - MONGODB_URI=mongodb://root:tvIJ65GJMrF6ZaiNhieL0hsK7ehBruwogouLnJMcHUaBuPM5NOKoQqLj7qbczDnj@f4ks8cg:27017/?directConnection=true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - front-end
      - back-end
