version: "3"
services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    restart: unless-stopped

  back-end:
    build:
      context: ./back-end
    container_name: back-end
    restart: unless-stopped
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - MONGODB_URI=${MONGODB_URI}

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - front-end
      - back-end
